stages:
  - build

build_project:
  only: 
   - master@csil-git1.cs.surrey.sfu.ca:cmpt276summer2018group8/ios-app
  stage: build
  script:
    - xcodebuild clean -workspace Vancouver-Fruit-Tree-Project.xcworkspace -scheme Vancouver-Fruit-Tree-Project | xcpretty
    - xcodebuild test -workspace Vancouver-Fruit-Tree-Project.xcworkspace -scheme Vancouver-Fruit-Tree-Project -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' | xcpretty -s
  tags:
    - ios_11-4 xcode_9-4
