//
//  PickEvents.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class PickEvents: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _time: String?
    var _date: String?
    var _latitude: String?
    var _longitude: String?
    var _randomString: String?
    var _teamID: String?
    
    class func dynamoDBTableName() -> String {

        return "vancouverfruittreepr-mobilehub-79870386-PickEvents"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_time"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_time" : "time",
               "_date" : "date",
               "_latitude" : "latitude",
               "_longitude" : "longitude",
               "_randomString" : "randomString",
               "_teamID" : "teamID",
        ]
    }
}
