//
//  PiackLocations.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class PickEvent: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _time: NSNumber?
    var _itemId: String?
    var _latitude: NSNumber?
    var _longitude: NSNumber?
    var _streetaddress: String?
    var _teamId: String?
    var _date: NSNumber?
    func recordNewEvent(UserID: String?, time: NSNumber?, latitude: NSNumber?, longtitude: NSNumber?, streetaddress: String?, teamId: String?, date: String?){
        self._userId = UserID
        self._time = time
        
    }
    func changeteam(TeamID: String?){
        self._teamId=TeamID
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        dynamoDbObjectMapper.save(self, completionHandler: {
            (error: Error?) -> Void in
            
            if let error = error {
                print("Amazon DynamoDB Save Error: \(error)")
                return
            }
            print("An item was saved.")
        })
    
    }
    func changetime(time: NSNumber?){
        
    }
    class func dynamoDBTableName() -> String {

        return "vancouverfruittreepr-mobilehub-79870386-PiackLocations"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_time"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_time" : "time",
               "_itemId" : "itemId",
               "_latitude" : "latitude",
               "_longitude" : "longitude",
               "_streetaddress" : "streetaddress",
        ]
    }
}
