//
//  Users.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSAuthCore
import AWSAuthUI
@objcMembers
class Users: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userID: String?
    var _firstName: String?
    var _role: String?
    var _secondName: String?
    var _email: String?
    func createNewUSer(FirsName: String?, SecondName: String?, role:String?, email:String?) {
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        self._userID=AWSIdentityManager.default().identityId
        self._firstName=FirsName
        self._secondName=SecondName
        self._email=email
        self._role=role
        dynamoDbObjectMapper.save(self, completionHandler: {
            (error: Error?) -> Void in
            
            if let error = error {
                print("Amazon DynamoDB Save Error: \(error)")
                return
            }
            print("An item was saved.")
        })
    }
    class func dynamoDBTableName() -> String {

        return "vancouverfruittreepr-mobilehub-79870386-users"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userID" : "userID",
               "_firstName" : "FirstName",
               "_role" : "Role",
               "_secondName" : "SecondName",
               "_email" : "email",
        ]
    }
}
