//
//  Team.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers // <-- don't remove this, it will break uploading
class Team: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _teamLeader: String?
    var _members: [String: [String: String] ]?
    var _pickEventHashKey: String?
    var _pickEventRangeKey: String?
    var _teamNumber: String?
    
    class func dynamoDBTableName() -> String {

        return "vancouverfruittreepr-mobilehub-79870386-Team"
    }
    
    class func hashKeyAttribute() -> String {

        return "_teamLeader"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_teamLeader" : "teamLeader",
               "_members" : "members",
               "_pickEventHashKey" : "pickEventHashKey",
               "_pickEventRangeKey" : "pickEventRangeKey",
               "_teamNumber" : "teamNumber",
        ]
    }
}
